# Generated by Django 3.2.5 on 2021-07-22 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование заявки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.TextField(choices=[('opened', 'открыта'), ('in_progress', 'в работе'), ('closed', 'закрыта')], verbose_name='Статус заявки')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='crm.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Список заявок',
            },
        ),
    ]
