# Generated by Django 3.2.5 on 2021-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Список категорий'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.TextField(choices=[('открыта', 'Открыта'), ('в работе', 'В работе'), ('закрыта', 'Закрыта')], verbose_name='Статус заявки'),
        ),
    ]
