# Generated by Django 3.2.5 on 2021-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210724_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
