# Generated by Django 3.2.5 on 2021-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_claim_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия пользователя')),
                ('notification', models.BooleanField(default=False, verbose_name='Уведомления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='owner',
            new_name='executor',
        ),
    ]
