# Generated by Django 3.2.5 on 2021-07-25 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_auto_20210725_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Автор заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель заявки'),
        ),
    ]
