# Generated by Django 3.2.5 on 2021-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210725_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='slug',
            field=models.SlugField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
