# Generated by Django 3.2.5 on 2021-07-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_claim_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='slug',
        ),
    ]
