# Generated by Django 3.2.5 on 2021-07-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_claim_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
