# Generated by Django 3.2.5 on 2021-07-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_claim_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
