# Generated by Django 3.2.5 on 2021-07-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_claim_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ('created',), 'verbose_name': 'Заявки', 'verbose_name_plural': 'Список заявок'},
        ),
    ]
