# Generated by Django 3.2.5 on 2021-07-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_claim_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_bids', to='crm.category', verbose_name='Категория'),
        ),
    ]
