# Generated by Django 3.2.5 on 2021-07-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_alter_claim_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='crm.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель заявки'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='crm.client', verbose_name='Автор заявки'),
        ),
    ]
