# Generated by Django 3.2.5 on 2021-07-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_claim_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='slug',
        ),
    ]
